{% set name = "scriptengine" %}
{% set version = "0.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scriptengine-{{ version }}.tar.gz
  sha256: f6cb893330a0d659a405435d9c843b24936203de9f89d7f7cbd48e277c4de8e7

build:
  entry_points:
    - se = scriptengine.cli.se:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - deepdiff >=6.2.2
    - deepmerge
    - jinja2
    - python >=3.6
    - python-dateutil
    - pyyaml

test:
  imports:
    - scriptengine
  commands:
    - pip check
    - se --help
  requires:
    - pip

about:
  home: https://github.com/uwefladrich/scriptengine
  summary: A lightweight and extensible framework for executing scripts written in YAML
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - uwefladrich
    - zklaus
